app/app/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

from . import views


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.HomeView.as_view(), name='home'),
    path('store/', include('store.urls')),
    path('cart/', include('carts.urls')),
    path('accounts/', include('accounts.urls')),
    path('orders/', include('orders.urls')),
    path('/health_check/', include('health_check.urls'))
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

app/carts/urls.py
from django.urls import path
from . import views


app_name = 'carts'

urlpatterns = [
    path('', views.CartView.as_view(), name='cart'),
    path('add-cart/<int:product_id>/', views.CartAddView.as_view(), name='add-cart'),
    path('remove-cart/<int:product_id>/<int:cart_item_id>/', views.CartRemoveView.as_view(), name='remove-cart'),
    path(
        'remove-cart-item/<int:product_id>/<int:cart_item_id>/',
        views.CartItemRemoveView.as_view(),
        name='remove-cart-item'
    ),

    path('checkout/', views.CheckoutView.as_view(), name='checkout'),
]

app/orders/urls.py
from django.urls import path
from . import views

app_name = 'orders'

urlpatterns = [
    path('place-order/', views.PlaceOrderView.as_view(), name='place-order'),
    path('payments/', views.PaymentsView.as_view(), name='payments'),
    path('order-complete/', views.OrderCompleteView.as_view(), name='order-complete'),
]

app/store/urls.py
from django.urls import path
from . import views

app_name = 'store'

urlpatterns = [
    path('', views.StoreView.as_view(), name='store'),
    path('category/<slug:category_slug>/', views.StoreView.as_view(), name='products-by-category'),
    path('category/<slug:category_slug>/<slug:product_slug>/', views.ProductDetailView.as_view(), name='product-detail'),
    path('search/', views.SearchView.as_view(), name='search'),
    path('submit_review/<int:product_id>/', views.SubmitReviewView.as_view(), name='submit-review'),
    path('add-wishlist/', views.AddWishListView.as_view(), name='add-wishlist'),
    path('my-wishlist/', views.WishListView.as_view(), name='my-wishlist'),
]

app/accounts/models.py
from django.db import models
from django.contrib.auth.models import AbstractBaseUser, BaseUserManager

import os


class MyAccountManager(BaseUserManager):

    def create_user(
            self, first_name, last_name, username, email, password=None
    ):
        if not email:
            raise ValueError('User must have an email address.')

        if not username:
            raise ValueError('User must have an username.')

        user = self.model(
            email=self.normalize_email(email),
            username=username,
            first_name=first_name,
            last_name=last_name
        )

        user.set_password(password)
        user.save(using=self._db)
        return user

    def create_superuser(
            self, first_name, last_name, email, username, password
    ):
        user = self.create_user(
            email=self.normalize_email(email),
            username=username,
            password=password,
            first_name=first_name,
            last_name=last_name
        )
        user.is_admin = True
        user.is_active = True
        user.is_staff = True
        user.is_superadmin = True
        user.save(using=self._db)
        return user


class Account(AbstractBaseUser):
    first_name = models.CharField(max_length=50)
    last_name = models.CharField(max_length=50)
    username = models.CharField(max_length=50, unique=True)
    email = models.EmailField(max_length=100, unique=True)
    phone_number = models.CharField(max_length=50, unique=True)
    date_joined = models.DateTimeField(auto_now_add=True)
    last_login = models.DateTimeField(auto_now_add=True)
    is_admin = models.BooleanField(default=False)
    is_staff = models.BooleanField(default=False)
    is_active = models.BooleanField(default=False)
    is_superadmin = models.BooleanField(default=False)

    USERNAME_FIELD = 'email'
    REQUIRED_FIELDS = ['username', 'first_name', 'last_name']

    objects = MyAccountManager()

    def full_name(self):
        return f'{self.first_name} {self.last_name}'

    def __str__(self):
        return self.email

    def has_perm(self, perm, obj=None):
        return self.is_admin

    def has_module_perms(self, add_label):
        return True


class UserProfile(models.Model):

    def image_upload_to(self, instance=None):
        if instance:
            return os.path.join('user_profile', self.user.email, instance)
        return None

    user = models.OneToOneField(Account, related_name='profile', on_delete=models.CASCADE)
    address_line_1 = models.CharField(max_length=100, blank=True)
    address_line_2 = models.CharField(max_length=100, blank=True)
    picture = models.ImageField(default='user_profile/default/default_user.png',
                                upload_to=image_upload_to)
    city = models.CharField(blank=True, max_length=20)
    state = models.CharField(blank=True, max_length=20)

    def __str__(self):
        return self.user.first_name

    def full_address(self):
        return f'{self.address_line_1} {self.address_line_2}'

app/carts/models.py
from django.db import models
from store.models import Product, Variation
from django.contrib.auth import get_user_model


User = get_user_model()


class Cart(models.Model):
    cart_id = models.CharField(max_length=250, blank=True)
    date_added = models.DateField(auto_now_add=True)

    def __str__(self):
        return self.cart_id


class CartItem(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE, null=True)
    product = models.ForeignKey(Product, on_delete=models.CASCADE)
    variations = models.ManyToManyField(Variation, blank=True)
    cart = models.ForeignKey(Cart, related_name='cart_item', on_delete=models.CASCADE, null=True)
    quantity = models.IntegerField()
    is_active = models.BooleanField(default=True)

    def sub_total(self):
        return self.product.price * self.quantity

    def __unicode__(self):
        return self.product

app/store/models.py
from django.db import models
from django.urls import reverse
from category.models import Category
from django.contrib.auth import get_user_model
from django.db.models import Avg

import os


User = get_user_model()


class Product(models.Model):

    def image_upload_to(self, instance=None):
        if instance:
            return os.path.join('store/products', self.name, instance)
        return None

    name = models.CharField(max_length=200, unique=True)
    slug = models.SlugField(max_length=200, unique=True)
    description = models.TextField(max_length=500, blank=True)
    price = models.IntegerField()
    image = models.ImageField(upload_to=image_upload_to)
    stock = models.IntegerField()
    is_available = models.BooleanField(default=True)
    category = models.ForeignKey(Category, on_delete=models.CASCADE)
    created_date = models.DateTimeField(auto_now_add=True)
    modified_date = models.DateTimeField(auto_now=True)
    users_wishlist = models.ManyToManyField(User, related_name='wishlist', blank=True)

    def get_url(self):
        return reverse('store:product-detail', args=[self.category.slug, self.slug])

    def __str__(self):
        return self.name

    def average_review(self):
        reviews = self.review.aggregate(average=Avg('rating'))
        return reviews['average'] if reviews['average'] else 0


class VariationManager(models.Manager):
    def colors(self):
        return super().filter(category='color', is_active=True)

    def sizes(self):
        return super().filter(category='size', is_active=True)


category_choice = (
    ('color', 'color'),
    ('size', 'size'),
)


class Variation(models.Model):
    product = models.ForeignKey(Product, on_delete=models.CASCADE)
    category = models.CharField(max_length=100, choices=category_choice)
    value = models.CharField(max_length=100)
    is_active = models.BooleanField(default=True)
    created_date = models.DateTimeField(auto_now=True)

    objects = VariationManager()

    def __str__(self):
        return self.value


class ReviewRating(models.Model):
    product = models.ForeignKey(Product, related_name='review', on_delete=models.CASCADE)
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    subject = models.CharField(max_length=100, blank=True)
    review = models.TextField(max_length=500, blank=True)
    rating = models.FloatField()
    ip = models.GenericIPAddressField(blank=True, null=True)
    status = models.BooleanField(default=True)
    created_date = models.DateTimeField(auto_now_add=True)
    updated_date = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.subject


class ProductGallery(models.Model):

    def image_upload_to(self, instance=None):
        if instance:
            return os.path.join('store/products', self.product.name, instance)
        return None

    product = models.ForeignKey(Product, related_name='gallery', default=None, on_delete=models.CASCADE)
    image = models.ImageField(upload_to=image_upload_to, max_length=255)

    def __str__(self):
        return self.product.name

    class Meta:
        verbose_name = 'productgallery'
        verbose_name_plural = 'product gallery'


# class WishList(models.Model):
#     user = models.ForeignKey(User, related_name='wishlist', on_delete=models.CASCADE)
#     product = models.ForeignKey(Product, related_name='wishlist', on_delete=models.CASCADE)
#
#     class Meta:
#         unique_together = ['user', 'product']

app/store/forms.py
from django import forms
from .models import ReviewRating


class ReviewForm(forms.ModelForm):

    class Meta:
        model = ReviewRating
        fields = ['subject', 'review', 'rating']

app/store/views.py
from django.views.generic import ListView, DetailView, View, CreateView
from django.shortcuts import get_object_or_404, render, redirect
from django.db.models import Q
from django.contrib import messages
from django.http import JsonResponse
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth import get_user_model

from .models import Product, ReviewRating
from category.models import Category
from carts.models import CartItem
from orders.models import OrderProduct
from carts.views import _cart_id
from .forms import ReviewForm


User = get_user_model()


class StoreView(ListView):
    """List all products of store or filter by category."""
    context_object_name = 'products'
    template_name = 'store/store.html'
    paginate_by = 6

    def get_queryset(self):
        try:
            if self.kwargs['category_slug']:
                category = get_object_or_404(Category, slug=self.kwargs['category_slug'])
                queryset = Product.objects.filter(category=category, is_available=True).order_by('-modified_date')

        except KeyError:
            queryset = Product.objects.filter(is_available=True).order_by('-modified_date')
        else:
            queryset = Product.objects.filter(is_available=True).order_by('-modified_date')

        if self.request.GET.get('size'):
            queryset = queryset.filter(variation__value=self.request.GET.get('size')).order_by('-modified_date')

        if self.request.GET.get('start_price') and self.request.GET.get('end_price'):
            queryset = queryset.filter(
                price__range=(self.request.GET.get('start_price'), self.request.GET.get('end_price'))
            ).order_by('-modified_date')

        return queryset

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['product_count'] = self.get_queryset().count()
        try:
            context['category'] = self.kwargs['category_slug'].capitalize()
        except KeyError:
            context['category'] = 'All Products'

        if self.request.GET.get('size'):
            context['size_filter'] = self.request.GET.get('size')

        return context


class ProductDetailView(DetailView):
    """Product detail view."""
    model = Product
    template_name = 'store/product_detail.html'
    slug_url_kwarg = 'product_slug'
    context_object_name = 'single_product'

    def get_object(self, queryset=None):
        queryset = self.get_queryset()
        try:
            return queryset.get(
                category__slug=self.kwargs['category_slug'], slug=self.kwargs[self.slug_url_kwarg]
            )
        except Exception as e:
            raise e

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['in_cart'] = CartItem.objects.filter(
            cart__cart_id=_cart_id(self.request), product=context['single_product']
        ).exists()

        try:
            context['order_product'] = OrderProduct.objects.filter(
                user=self.request.user, product_id=self.get_object().id
            ).exists()
        except (OrderProduct.DoesNotExist, TypeError):
            context['order_product'] = None

        # Get the reviews
        context['reviews'] = context['single_product'].review

        return context


class SearchView(View):
    """View for searching product."""

    def get(self, request, *args, **kwargs):
        if 'keyword' in request.GET:
            keyword = request.GET['keyword']
            if keyword:
                products = Product.objects.filter(
                    Q(description__icontains=keyword) | Q(name__icontains=keyword)
                ).order_by('-created_date')
                product_count = products.count()

            context = {
                'products': products,
                'product_count': product_count,
            }

            return render(request, 'store/store.html', context)


class SubmitReviewView(LoginRequiredMixin, CreateView):
    form_class = ReviewForm
    pk_url_kwarg = 'product_id'

    def post(self, request, *args, **kwargs):
        url = request.META.get('HTTP_REFERER')
        try:
            reviews = ReviewRating.objects.get(user__id=request.user.id, product__id=kwargs['product_id'])
            form = ReviewForm(request.POST, instance=reviews)
            form.save()
            messages.success(request, 'Thank you! Your review has been updated.')

            return redirect(url)

        except ReviewRating.DoesNotExist:
            form = ReviewForm(request.POST)
            if form.is_valid():
                review = form.save(commit=False)
                review.ip = request.META.get('REMOTE_ADDR')
                review.product_id = kwargs['product_id']
                review.user_id = request.user.id
                review.save()
                messages.success(request, 'Thank you! Your review has been submitted.')

                return redirect(url)


class AddWishListView(LoginRequiredMixin, View):

    def post(self, request, *args, **kwargs):
        product_id = request.POST['product']
        product = Product.objects.get(pk=product_id)

        if product.users_wishlist.filter(email=request.user.email).exists():
            product.users_wishlist.remove(request.user)
            data = {'bool': False}
        else:
            product.users_wishlist.add(request.user)
            data = {'bool': True}

        return JsonResponse(data)


class WishListView(LoginRequiredMixin, ListView):
    model = User
    template_name = 'accounts/wishlist.html'
    context_object_name = 'wishlist'

    def get_queryset(self):
        return self.request.user.wishlist.all().order_by('-id')

app/templates/store/cart.html
{% extends 'base.html' %}
{% load static %}
{% block content %}

<section class="section-content padding-y bg">
<div class="container">

<!-- ============================ COMPONENT 1 ================================= -->
{% if not cart_items %}
	<h2 class="text-center">Your Shopping Cart is Empty</h2>
	<br>
	<div class="text-center">
		<a href="{% url 'store:store' %}" class="btn btn-primary">Continue Shopping?</a>
	</div>
{% else %}
<div class="row">
	<aside class="col-lg-9">
<div class="card">
<table class="table table-borderless table-shopping-cart">
<thead class="text-muted">
<tr class="small text-uppercase">
  <th scope="col">Product</th>
  <th scope="col" width="120">Quantity</th>
  <th scope="col" width="120">Price</th>
  <th scope="col" class="text-end" width="200"> </th>
</tr>
</thead>
<tbody>

{% for cart_item in cart_items %}
<tr>
	<td>
		<figure class="itemside align-items-center">
			<div class="aside"><img src="{{ cart_item.product.image.url }}" class="img-sm"></div>
			<figcaption class="info">
				<a href="{{ cart_item.product.get_url }}" class="title text-dark">{{ cart_item.product.name }}</a>
				<p class="text-muted small">
					{% if cart_item.variations.all %}
						{% for item in cart_item.variations.all %}
							{{ item.category|capfirst }} : {{ item.value|capfirst }} <br>
						{% endfor %}
					{% endif %}
				</p>
			</figcaption>
		</figure>
	</td>
	<td>
		<!-- col.// -->
			<div class="col">
				<div class="input-group input-spinner">
					<div class="input-group-prepend">
					<form action="{% url 'carts:remove-cart' cart_item.product.id cart_item.id %}" method="POST">
						{% csrf_token %}
						<button class="btn btn-light" type="submit" id="button-minus"> <i class="fa fa-minus"></i> </button>
					</form>
					</div>
					<input type="text" class="form-control" name="quantity{{ cart_item.id }}" value="{{ cart_item.quantity }}">
					<div class="input-group-append">
					<form class="add-to-cart-in-cart-{{ cart_item.id }}" method="POST">
						{% csrf_token %}
						{% for item in cart_item.variations.all %}
						<input type="hidden" name="{{ item.category|lower }}" value="{{ item.value|capfirst }}">
						{% endfor %}
						<button class="btn btn-light add-to-cart" type="submit" id="button-plus"
								data-product="{{ cart_item.product.id }}" data-cart="{{ cart_item.id }}"> <i class="fa fa-plus"></i> </button>
					</form>
					</div>
				</div> <!-- input-group.// -->
			</div> <!-- col.// -->
	</td>
	<td>
		<div class="price-wrap">
			<var class="price">$ {{ cart_item.sub_total }}</var>
			<small class="text-muted"> $ {{ cart_item.product.price }} each </small>
		</div> <!-- price-wrap .// -->
	</td>
	<td class="text-end">
		<form action="{% url 'carts:remove-cart-item' cart_item.product.id cart_item.id %}" method="post">
		{% csrf_token %}
			<button type="submit" class="btn btn-danger"
					onclick="return confirm('Are you sure you want to delete this item>)"> Remove</button>
		</form>
	</td>
</tr>
{% endfor %}
</tbody>
</table>
</div> <!-- card.// -->

	</aside> <!-- col.// -->
	<aside class="col-lg-3">

		<div class="card">
		<div class="card-body">
			<dl class="dlist-align">
			  <dt>Total price:</dt>
			  <dd class="text-end">$ {{ total }}</dd>
			</dl>
			<dl class="dlist-align">
			  <dt>Tax:</dt>
			  <dd class="text-end"> $ {{ tax }}</dd>
			</dl>
			<dl class="dlist-align">
			  <dt>Total:</dt>
			  <dd class="text-end text-dark b"><strong>$ {{ grand_total }}</strong></dd>
			</dl>
			<hr>
			<p class="text-center mb-3">
				<img src="{% static './images/misc/payments.png' %}" height="26">
			</p>
			<a href="{% url 'carts:checkout' %}" class="btn btn-primary btn-block me-2" style="width: 110px;"> Checkout </a>
			<a href="{% url 'store:store' %}" class="btn btn-light btn-block">Continue Shopping</a>
		</div> <!-- card-body.// -->
		</div> <!-- card.// -->

</aside> <!-- col.// -->


</div> <!-- row.// -->
{% endif %}
<!-- ============================ COMPONENT 1 END .// ================================= -->

</div> <!-- container .//  -->
</section>
<!-- ========================= SECTION CONTENT END// ========================= -->
{% endblock %}

{% block js %}
<script src="{% static 'js/ajax_for_cart.js' %}" type="text/javascript"></script>
{% endblock %}

app/templates/store/checkout.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
<style>
    #id_phone_number {
        width: 291.5px;
    }
</style>
<section class="section-content padding-y bg">
<div class="container">

<!-- ============================ COMPONENT 1 ================================= -->
<div class="row">
	<aside class="col-lg-6">
<div class="card">
    <div class="card-body">
        <h4 class="card-title mb-4">Billing Address</h4>
        <form action="{% url 'orders:place-order' %}" onsubmit="return addDialCode(this)" id="formBill" method="POST">
            {% csrf_token %}

            <div class="row mb-3">
                <div class="col form-group">
                    <label for="" class="form-label">First Name</label>
                    {{ form.first_name }}
                </div>
                <div class="col form-group">
                    <label for="" class="form-label">Last Name</label>
<!--                    <input type="text" name="last_name" class="form-control" required>-->
                    {{ form.last_name }}
                </div>
            </div>
            <div class="row mb-3">
                <div class="col form-group">
                    <label for="" class="form-label">Email</label>
                    {{ form.email }}
<!--                    <input type="text" name="email" class="form-control" required>-->
                </div>
                <div class="col form-group">
                    <label for="" class="form-label">Phone Number</label>
                    {{ form.phone }}
                </div>
            </div>
            <div class="row mb-3">
                <div class="col form-group">
                    <label for="" class="form-label">Address Line 1</label>
                    {{ form.address_line_1 }}
<!--                    <input type="text" name="address_line_1" class="form-control" required>-->
                </div>
                <div class="col form-group">
                    <label for="" class="form-label">Address Line 2</label>
                    {{ form.address_line_2 }}
<!--                    <input type="text" name="address_line_2" class="form-control">-->
                </div>
            </div>
            <div class="row mb-3">
                <div class="col form-group">
                    <label for="" class="form-label">City</label>
                    {{ form.city }}
<!--                    <input type="text" name="city" class="form-control" required>-->
                </div>
                <div class="col form-group">
                    <label for="" class="form-label">State</label>
                    {{ form.state }}
<!--                    <input type="text" name="state" class="form-control" required>-->
                </div>
            </div>
            <div class="mb-3">
                <label for="" class="form-label">Order Note</label>
                <textarea name="order_note" rows="2" class="form-control" id="orderNote"></textarea>
            </div>

    </div>
</div> <!-- card.// -->

	</aside> <!-- col.// -->
	<aside class="col-lg-6">

		<div class="card">
		<div class="card-body">
            <table class="table table-borderless table-shopping-cart">
            <thead class="text-muted">
            <tr class="small text-uppercase">
              <th scope="col">Product</th>
              <th scope="col" width="120">Quantity</th>
              <th scope="col" width="120">Price</th>
            </tr>
            </thead>
            <tbody>

            {% for cart_item in cart_items %}
            <tr>
                <td>
                    <figure class="itemside align-items-center">
                        <div class="aside"><img src="{{ cart_item.product.image.url }}" class="img-sm"></div>
                        <figcaption class="info">
                            <a href="{{ cart_item.product.get_url }}" class="title text-dark">{{ cart_item.product.name }}</a>
                            <p class="text-muted small">
                                {% if cart_item.variations.all %}
                                    {% for item in cart_item.variations.all %}
                                        {{ item.category|capfirst }} : {{ item.value|capfirst }} <br>
                                    {% endfor %}
                                {% endif %}
                            </p>
                        </figcaption>
                    </figure>
                </td>
                <td>
                    <!-- col.// -->
                    <label for="">{{ cart_item.quantity }}</label>
                </td>
                <td>
                    <div class="price-wrap">
                        <var class="price">$ {{ cart_item.sub_total }}</var>
                        <small class="text-muted"> $ {{ cart_item.product.price }} each </small>
                    </div> <!-- price-wrap .// -->
                </td>

            </tr>
            {% endfor %}
            </tbody>
            </table>
            <div class="row">
                <div class="d-grid gap-2 col-6">
                    <button id="formSubmit" name="submit" class="btn btn-primary btn-block me-2">Place Order</button>
                </div>
                <div class="d-grid gap-2 col-6">
                    <a href="{% url 'store:store' %}" class="btn btn-light btn-block">Continue Shopping</a>
                </div>
            </div>
            </form>
		</div> <!-- card-body.// -->
		</div> <!-- card.// -->

</aside> <!-- col.// -->


</div> <!-- row.// -->
<!-- ============================ COMPONENT 1 END .// ================================= -->

</div> <!-- container .//  -->
</section>
<!-- ========================= SECTION CONTENT END// ========================= -->

{% endblock %}