app/app/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

from . import views


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.HomeView.as_view(), name='home'),
    path('store/', include('store.urls')),
    path('cart/', include('carts.urls')),
    path('accounts/', include('accounts.urls')),
    path('orders/', include('orders.urls')),
    path('/health_check/', include('health_check.urls'))
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

app/carts/urls.py
from django.urls import path
from . import views


app_name = 'carts'

urlpatterns = [
    path('', views.CartView.as_view(), name='cart'),
    path('add-cart/<int:product_id>/', views.CartAddView.as_view(), name='add-cart'),
    path('remove-cart/<int:product_id>/<int:cart_item_id>/', views.CartRemoveView.as_view(), name='remove-cart'),
    path(
        'remove-cart-item/<int:product_id>/<int:cart_item_id>/',
        views.CartItemRemoveView.as_view(),
        name='remove-cart-item'
    ),

    path('checkout/', views.CheckoutView.as_view(), name='checkout'),
]

app/store/urls.py
from django.urls import path
from . import views

app_name = 'store'

urlpatterns = [
    path('', views.StoreView.as_view(), name='store'),
    path('category/<slug:category_slug>/', views.StoreView.as_view(), name='products-by-category'),
    path('category/<slug:category_slug>/<slug:product_slug>/', views.ProductDetailView.as_view(), name='product-detail'),
    path('search/', views.SearchView.as_view(), name='search'),
    path('submit_review/<int:product_id>/', views.SubmitReviewView.as_view(), name='submit-review'),
    path('add-wishlist/', views.AddWishListView.as_view(), name='add-wishlist'),
    path('my-wishlist/', views.WishListView.as_view(), name='my-wishlist'),
]

app/accounts/models.py
from django.db import models
from django.contrib.auth.models import AbstractBaseUser, BaseUserManager

import os


class MyAccountManager(BaseUserManager):

    def create_user(
            self, first_name, last_name, username, email, password=None
    ):
        if not email:
            raise ValueError('User must have an email address.')

        if not username:
            raise ValueError('User must have an username.')

        user = self.model(
            email=self.normalize_email(email),
            username=username,
            first_name=first_name,
            last_name=last_name
        )

        user.set_password(password)
        user.save(using=self._db)
        return user

    def create_superuser(
            self, first_name, last_name, email, username, password
    ):
        user = self.create_user(
            email=self.normalize_email(email),
            username=username,
            password=password,
            first_name=first_name,
            last_name=last_name
        )
        user.is_admin = True
        user.is_active = True
        user.is_staff = True
        user.is_superadmin = True
        user.save(using=self._db)
        return user


class Account(AbstractBaseUser):
    first_name = models.CharField(max_length=50)
    last_name = models.CharField(max_length=50)
    username = models.CharField(max_length=50, unique=True)
    email = models.EmailField(max_length=100, unique=True)
    phone_number = models.CharField(max_length=50, unique=True)
    date_joined = models.DateTimeField(auto_now_add=True)
    last_login = models.DateTimeField(auto_now_add=True)
    is_admin = models.BooleanField(default=False)
    is_staff = models.BooleanField(default=False)
    is_active = models.BooleanField(default=False)
    is_superadmin = models.BooleanField(default=False)

    USERNAME_FIELD = 'email'
    REQUIRED_FIELDS = ['username', 'first_name', 'last_name']

    objects = MyAccountManager()

    def full_name(self):
        return f'{self.first_name} {self.last_name}'

    def __str__(self):
        return self.email

    def has_perm(self, perm, obj=None):
        return self.is_admin

    def has_module_perms(self, add_label):
        return True


class UserProfile(models.Model):

    def image_upload_to(self, instance=None):
        if instance:
            return os.path.join('user_profile', self.user.email, instance)
        return None

    user = models.OneToOneField(Account, related_name='profile', on_delete=models.CASCADE)
    address_line_1 = models.CharField(max_length=100, blank=True)
    address_line_2 = models.CharField(max_length=100, blank=True)
    picture = models.ImageField(default='user_profile/default/default_user.png',
                                upload_to=image_upload_to)
    city = models.CharField(blank=True, max_length=20)
    state = models.CharField(blank=True, max_length=20)

    def __str__(self):
        return self.user.first_name

    def full_address(self):
        return f'{self.address_line_1} {self.address_line_2}'

app/templates/includes/alerts.html
{% if messages %}
    {% for message in messages %}
    <div id="message" class="container">
    <div {% if message.tags %} class="alert alert-{{ message.tags }}"{% endif %} role="alert">
<!--        <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>-->
        {% if message.level == DEFAULT_MESSAGE_LEVELS.ERROR %}Error: {% endif %}
        {{ message }}
    </div>
    </div>
    {% endfor %}
{% endif %}

app/templates/includes/dashboard_sidebar.html
<aside class="col-md-3">
    <!--   SIDEBAR   -->
    <ul class="list-group">
        <a class="list-group-item {% if '/accounts/' == request.path %}active{% endif %}" href="{% url 'dashboard' %}"> Dashboard</a>
        <a class="list-group-item {% if '/my-orders/' in request.path %}active{% endif %}" href="{% url 'my-orders' %}"> My Orders </a>
        <a class="list-group-item {% if '/my-wishlist/' in request.path %}active{% endif %}" href="{% url 'store:my-wishlist' %}"> Wishlist </a>
        <a class="list-group-item {% if '/edit-profile/' in request.path %}active{% endif %}" href="{% url 'edit-profile' %}"> Edit Profile</a>
        <a class="list-group-item {% if '/change-password/' in request.path %}active{% endif %}" href="{% url 'change-password' %}"> Change Password </a>
        <a class="list-group-item" href="#"> Received orders </a>
    </ul>
    <br>
    <a class="btn btn-light btn-block" href="{% url 'logout' %}"> <i class="fa fa-power-off"></i> <span class="text">Log out</span> </a>
    <!--   SIDEBAR .//END   -->
</aside>

app/templates/includes/footer.html
{% load static %}
<!-- ========================= FOOTER ========================= -->
<footer class="section-footer border-top">
	<div class="container">
		<section class="footer-bottom border-top row">
			<div class="col-md-3">
				<p class="text-muted"> &copy 2023 Dmytro Konstantinov </p>
			</div>
			<div class="col-md-6 text-md-center">
				<span  class="px-2">dmytro.konstantinov37@gmail.com</span>
<!--				<span  class="px-2"></span>-->
				<span  class="px-2">Kyiv, Ukraine</span>
			</div>
			<div class="col-md-3 text-md-end text-muted">
				<i class="fa fa-lg fa-cc-visa"></i>
				<i class="fa fa-lg fa-cc-mastercard"></i>
			</div>
		</section>
	</div><!-- //container -->
</footer>
<!-- ========================= FOOTER END // ========================= -->
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.6.3/jquery.min.js"></script>
<script src="{% static 'js/bundle.js' %}"></script>
<script src="{% static 'js/owl.carousel.min.js' %}"></script>
<!-- custom javascript -->
<script src="{% static 'js/script.js' %}" type="text/javascript"></script>
<script>
	$(document).ready(function(){
		$('.thumb a').click(function(e){
			e.preventDefault();
			$('.mainImage img').attr('src', $(this).attr('href'));
		})
	})
</script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/intl-tel-input/17.0.8/js/intlTelInput.min.js"></script>
<script>
	const phoneInputField = document.querySelector("#id_phone_number");
	const phoneInput = window.intlTelInput(phoneInputField, {
	 initialCountry: "ua",
	 preferredCountries: ["ua", "us", "gb"],
	 separateDialCode: true,
	 utilsScript:
	   "https://cdnjs.cloudflare.com/ajax/libs/intl-tel-input/17.0.8/js/utils.js",
	});
</script>

app/templates/includes/navbar.html
{% load static %}
<header class="section-header">
  <nav class="navbar p-md-0 navbar-expand-sm navbar-light border-bottom">
  <div class="container">
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarTop4" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarTop4">
      <ul class="navbar-nav me-auto">
          <li class="nav-item dropdown">
              <a href="#" class="nav-link">   English </a>

          </li>
          <li class="nav-item dropdown">
              <a href="#" class="nav-link"> USD </a>
          </li>
      </ul>
      <ul class="navbar-nav">
          <li><a href="#" class="nav-link"> <i class="fa fa-envelope"></i> Email </a></li>
          <li><a href="#" class="nav-link"> <i class="fa fa-phone"></i> Call us </a></li>
      </ul> <!-- list-inline //  -->
    </div> <!-- navbar-collapse .// -->
  </div> <!-- container //  -->
  </nav>

  <section class="header-main border-bottom">
      <div class="container">
  <div class="row align-items-center">
      <div class="col-lg-2 col-md-3 col-6">
          <a href="{% url 'home' %}" class="brand-wrap">
              <img class="logo" src="{% static './images/logo.png' %}" style="width: 170px;">
          </a> <!-- brand-wrap.// -->
      </div>
      <div class="col-lg col-sm col-md col-6 flex-grow-0">
          <div class="category-wrap dropdown d-inline-block float-right">
              <button type="button" class="btn btn-primary dropdown-toggle" data-bs-toggle="dropdown">
                  <i class="fa fa-bars"></i> All category
              </button>
              <div class="dropdown-menu">
                  <a class="dropdown-item" href="{% url 'store:store' %}">All Products</a>
                  {% for category in links %}
                    <a class="dropdown-item" href="{{ category.get_url }}">{{ category.name }}</a>
                  {% endfor %}
              </div>
          </div>  <!-- category-wrap.// -->
      </div> <!-- col.// -->
      <div class="col-lg col-sm col-md col-6 flex-grow-0">
        <a href="{% url 'store:store' %}" class="btn btn-outline-primary">Store</a>
      </div>
      <div class="col-lg  col-md-6 col-sm-12 col">
          <form action="{% url 'store:search' %}" class="search" method="GET">
              <div class="input-group w-100">
                  <input type="text" class="form-control" style="width:60%;" placeholder="Search" name="keyword">

                  <div class="input-group-append">
                    <button class="btn btn-primary" type="submit">
                      <i class="fa fa-search"></i>
                    </button>
                  </div>
              </div>
          </form> <!-- search-wrap .end// -->
      </div> <!-- col.// -->
      <div class="col-lg-3 col-sm-6 col-8 order-2 order-lg-3">
                  <div class="d-flex justify-content-end mb-3 mb-lg-0">
                      {% if user.is_authenticated %}
                      <div class="widget-header">
                          <small class="title text-muted">Welcome {{ user.first_name }}!</small>
                          <div>
                              <a href="{% url 'dashboard' %}">Dashboard</a> <span class="dark-transp"> | </span>
                              <a href="{% url 'logout' %}"> Logout</a>
                          </div>
                      </div>
                      {% else %}
                      <div class="widget-header">
                          <small class="title text-muted">Welcome guest!</small>
                          <div>
                              <a href="{% url 'login' %}">Sign in</a> <span class="dark-transp"> | </span>
                              <a href="{% url 'register' %}"> Register</a>
                          </div>
                      </div>
                      {% endif %}
                      <a href="{% url 'store:my-wishlist' %}" class="widget-header ps-3 ms-3">
                          <div class="icon icon-sm rounded-circle border"><i class="fa fa-heart"></i></div>
<!--                          <span class="badge badge-pill badge-danger notify" id=""> cart_count </span>-->
                      </a>
                      <a href="{% url 'carts:cart' %}" class="widget-header ps-3 ms-1">
                          <div class="icon icon-sm rounded-circle border"><i class="fa fa-shopping-cart"></i></div>
                          <span class="badge badge-pill badge-danger notify" id="cart_count">{{ cart_count }}</span>
                      </a>
                  </div> <!-- widgets-wrap.// -->
              </div> <!-- col.// -->
  </div> <!-- row.// -->
      </div> <!-- container.// -->
  </section> <!-- header-main .// -->



  </header> <!-- section-header.// -->